name: 'white_city_arbox'
version: '1.0.0'
profile: 'white_city_arbox'

model-paths: ["models"]
test-paths:  ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  white_city_arbox:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
