white_city_arbox:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('SUPABASE_DB_POOLER_HOST') }}"
      port: 5432
      dbname: postgres
      user: "{{ env_var('SUPABASE_DB_POOLER_USER') }}"
      password: "{{ env_var('SUPABASE_DB_PASSWORD') }}"
      schema: public
      threads: 4
      connect_timeout: 10
      keepalives_idle: 0
      sslmode: require
